import makeWASocket, { makeAutoRestartingWASocket } from './Socket';
export * from '../WAProto';
export * from './Utils';
export * from './Types';
export * from './Store';
export * from './Defaults';
export * from './WABinary';
export * from './WAM';
export * from './WAUSync';
export * from './Socket/username';
export type WASocket = ReturnType<typeof makeWASocket>;
export { makeWASocket, makeAutoRestartingWASocket };
export default makeWASocket;
